# Try Catch

try{
//代码区
}catch(Exception e){
//异常处理
}
代码区如果有错误，就会返回所写异常的处理。

http://blog.sina.com.cn/s/blog_4f1c99de0100tyty.html

http://blog.csdn.net/nvd11/article/details/19047047
